server:
  port: 8088
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lift?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: jerico
    password: 12345678

mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jerico.spring.mybatis.entity
  configuration:
    mapUnderscoreToCamelCase: true #pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.jerico.spring.mybatis:
        dao: debug