spring:
  datasource:
    username: jerico
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
# 配置扫描xml文件的路径
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/config/mybatis-config.xml